version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    image: testy-mctestface
    environment:
      DATABASE_URL: ${DATABASE_URL}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      NEXT_PUBLIC_CLIENTVAR: ${NEXT_PUBLIC_CLIENTVAR}
      VIRTUAL_HOST: ${VIRTUAL_HOST}