version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    expose:
      - "3000"
    image: t3-app
    environment:
      - DATABASE_URL=database_url_goes_here
      - VIRTUAL_HOST=testy-mctestface.kernel.community
      - LETSENCRYPT_HOST=testy-mctestface.kernel.community
    networks: ["serve"]

networks:
  serve:
    external: true
